---
kind: pipeline
type: kubernetes
name: build-and-publish

trigger:
  event:
    - push

resources:
  requests:
    cpu: 100
    memory: 500MiB

steps:
  - name: publish
    image: public.ecr.aws/kanopy/buildctl-ecr@sha256:27a2afc2d4c0552e996644827256e876ba827dddbdb269c8fd186ebc477de72ar
    environment:
      REPOSITORY: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      AWS_ACCESS_KEY_ID:
        from_secret: ecr_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: ecr_secret_key
    commands:
    - repo_helper
    - buildctl build --output=type=image,name=795250896452.dkr.ecr.us-east-1.amazonaws.com/devops/evergreen:buildckit-build,push=true --local context=. --dockerfile=./build/ --frontend=dockerfile.v0 --opt target=production --opt build-arg:GOOS=linux --opt build-arg:GOARCH=amd64 --opt build-arg:GOVERSION=1.20.7
    when:
      event:
        - push
