---
kind: pipeline
type: kubernetes
name: build-and-publish

trigger:
  event:
    - push

platform:
  os: linux
  arch: arm64

steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      dockerfile: build/Dockerfile
      target: production
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: devprod-platform/${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
        - ${DRONE_STAGE_ARCH}-latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
      build_args:
        - GOOS=${DRONE_STAGE_OS}
        - GOARCH=${DRONE_STAGE_ARCH}
        - GOVERSION=1.20.7
    when:
      event:
        - push
